FAIL
Kernel panic in run: PANIC at ../../threads/synch.c:242 in lock_release(): assertion `lock_held_by_current_thread (lock)' failed.
Call stack: 0x8004213fa2 0x800420aa32 0x8004207c86 0x8004206aeb 0x8004206068
Translation of call stack:
0x0000008004213fa2: debug_panic (lib/kernel/debug.c:32)
0x000000800420aa32: lock_release (threads/synch.c:244)
0x0000008004207c86: allocate_tid (threads/thread.c:659)
0x0000008004206aeb: thread_init (threads/thread.c:130)
0x0000008004206068: main (threads/init.c:83)
